<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWindowsForms>false</UseWindowsForms>
    <ApplicationIcon>..\ClipPlus.Windows\Resources\ClipPlus.ico</ApplicationIcon>
    <SelfContained>true</SelfContained>
    <PublishAot>true</PublishAot>
    <InvariantGlobalization>true</InvariantGlobalization>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
  </PropertyGroup>

  <ItemGroup Condition="'$(ClipPlusPayloadPath)' != ''">
    <EmbeddedResource Include="$(ClipPlusPayloadPath)" LogicalName="ClipPlus.exe" />
  </ItemGroup>
</Project>
